name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: b0wter
        password: ${{ secrets.DOCKER_HUB_PAT }}
        logout: true
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        push: true 
        tags: b0wter/spotify-shuffle:latest #$(date +%s)
