name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: b0wter
        password: ${{ secrets.DOCKER_HUB_PAT }}
        logout: true
    - name: Docker Setup Buildx
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
      uses: docker/setup-buildx-action@v2.0.0
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true 
        tags: b0wter/spotify-shuffle:latest #$(date +%s)