name: Docker Image CI

env: 
  docker_tag: b0wter/spotify-shuffle:$(date +%s)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: b0wter
        password: ${{ secrets.DOCKER_HUB_PAT }}
        logout: true
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true 
        tags: ${{ env.docker_tag }}
