name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/b0wter/spotify-shuffle:$(date +%s)

  publish:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: b0wter
        pas sword: ${{ docker_hub_pat }}
        logout: true
        
    
